gazebo_ros_control:
  pid_gains:
    front_left_wheel_joint: { p: 100.0, i: 0.01, d: 0.01 }
    front_right_wheel_joint: { p: 100.0, i: 0.01, d: 0.01 }
    back_left_wheel_joint: { p: 100.0, i: 0.01, d: 0.01 }
    back_right_wheel_joint: { p: 100.0, i: 0.01, d: 0.01 }
    
    camera_joint: { p: 100.0, i: 0.01, d: 0.01 }